services:
  - type: web
    name: kot-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: bash start.sh
    repo: https://github.com/mbijyl/kot-bot
    branch: main
    autoDeploy: true
